import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const $ = (id) => document.getElementById(id);
const seed = { title:"从垃圾星归来", genre:"科幻幻想 · 纯爱", logline:"被流放至垃圾星的修复师，带着一枚不该存在的星核回到帝国；他必须在旧爱与真相之间，重写自己的归途。", world:"垃圾星·赫墨拉：帝国最远端的废弃轨道坟场。\n星核：能够读取物质记忆的未知遗物，使用者会留下情感回声。\n帝国：以“净化协议”控制星际航路的中央政体。", timeline:"001｜坠入赫墨拉：主角苏醒，发现星核。\n013｜回归航线：与昔日恋人陆沉重逢。\n027｜协议裂缝：两人查出净化协议的真实用途。", characters:[{name:"沈砚",role:"主角 / 修复师",note:"冷静克制，能听见物质的记忆。"},{name:"陆沉",role:"舰长 / 旧爱",note:"忠于帝国，却开始怀疑命令。"}] };
let sb, user, novels=[], active, timer;
try { sb = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); } catch { $("auth-message").textContent="请先填写 config.js 里的 Publishable key。"; }

async function boot(){ if(!sb)return; const {data:{session}}=await sb.auth.getSession(); if(session) await enter(session.user); }
async function enter(current){user=current; $("auth-view").classList.add("hidden");$("app-view").classList.remove("hidden");$("user-email").textContent=user.email;await loadNovels();}
async function loadNovels(){const {data,error}=await sb.from("novels").select("*").order("updated_at",{ascending:false});if(error){status(error.message);return}novels=data||[];if(!novels.length){active={...seed};render();status("已载入示例作品；点击保存即可同步。") }else{active=novels[0];render();}}
function status(text){$("save-status").textContent=text;clearTimeout(timer);timer=setTimeout(()=>$("save-status").textContent="",4200)}
function render(){if(!active)return;$("title").value=active.title||"";$("genre").textContent=active.genre||"待定义";$("logline").value=active.logline||"";$("world").value=active.world||"";$("timeline").value=active.timeline||"";$("novel-list").innerHTML=novels.map(n=>`<button class="novel-item ${n.id===active.id?"active":""}" data-id="${n.id}">${esc(n.title)}</button>`).join("");$("novel-list").querySelectorAll("button").forEach(b=>b.onclick=()=>{active=novels.find(n=>n.id===b.dataset.id);render()});renderCharacters(); counts();}
function esc(s=""){return s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function renderCharacters(){const chars=active.characters||[];$("characters").innerHTML=chars.map((c,i)=>`<div class="character"><button class="delete" data-del="${i}">删除</button><input data-char="name" data-i="${i}" value="${esc(c.name)}" placeholder="人物名称"><input data-char="role" data-i="${i}" value="${esc(c.role)}" placeholder="身份 / 阵营"><textarea data-char="note" data-i="${i}" placeholder="人物简介">${esc(c.note)}</textarea></div>`).join("");$("characters").querySelectorAll("[data-char]").forEach(el=>el.oninput=e=>{active.characters[e.target.dataset.i][e.target.dataset.char]=e.target.value;counts()});$("characters").querySelectorAll("[data-del]").forEach(el=>el.onclick=()=>{active.characters.splice(el.dataset.del,1);renderCharacters();counts()});}
function counts(){ $("world-count").textContent=($('world').value.match(/\S+/g)||[]).length;$("character-count").textContent=(active.characters||[]).length;$("plot-count").textContent=($('timeline').value.split("\n").filter(Boolean)).length;}
function bindField(id,key){$(id).oninput=e=>{active[key]=e.target.value;counts()}}[ ["title","title"],["logline","logline"],["world","world"],["timeline","timeline"]].forEach(x=>bindField(...x));
$("signin").onclick=async()=>{const email=$("email").value.trim();if(!email)return;const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});$("auth-message").textContent=error?error.message:"登录链接已发送，请到邮箱打开。"};
$("signout").onclick=async()=>{await sb.auth.signOut();location.reload()};
$("new-novel").onclick=()=>{const title=prompt("小说名称：");if(title){active={...seed,id:undefined,title,characters:[]};render();status("新作品已创建，点击保存即可同步。");}};
$("add-character").onclick=()=>{active.characters=[...(active.characters||[]),{name:"新人物",role:"待定义",note:""}];renderCharacters();counts()};
$("save").onclick=async()=>{if(!active.title.trim())return status("请先填写小说标题。");status("保存中…");const record={...active,user_id:user.id,updated_at:new Date().toISOString()};delete record.id;const {data,error}=active.id?await sb.from("novels").update(record).eq("id",active.id).select().single():await sb.from("novels").insert(record).select().single();if(error)return status(error.message);active=data;const i=novels.findIndex(n=>n.id===data.id);if(i<0)novels.unshift(data);else novels[i]=data;render();status("已同步到云端 ✓")};
$("export").onclick=()=>{const text=`# ${active.title}\n\n> ${active.genre||""}\n\n## 一句话梗概\n${active.logline||""}\n\n## 世界观\n${active.world||""}\n\n## 人物\n${(active.characters||[]).map(c=>`- **${c.name}**｜${c.role}：${c.note}`).join("\n")}\n\n## 故事线\n${active.timeline||""}\n`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/markdown"}));a.download=`${active.title}-设定集.md`;a.click();};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");["world","characters","plot","ai"].forEach(t=>$(t+"-panel").classList.toggle("hidden",t!==b.dataset.tab))});
$("ask-ai").onclick=async()=>{const prompt=$("ai-prompt").value.trim();if(!prompt)return;$("ai-answer").textContent="思考中…";const {data,error}=await sb.functions.invoke("gpt-assistant",{body:{prompt,context:active}});$("ai-answer").textContent=error?`无法调用 GPT：${error.message}`:(data.text||data.error||"暂时没有回复。");};
boot();
